// src/components/MarriageCertificate.tsx
import { Document, Page, Text, StyleSheet, View } from '@react-pdf/renderer'

export interface CertificateProps {
  application: {
    husbandName: string
    wifeName: string
    dateOfMarriage: string
    witnessName: string
    witnessCitizenshipNo: string
  }
}

const styles = StyleSheet.create({
  page: {
    backgroundColor: '#fffaf3',
    padding: 50,
    flexDirection: 'column',
  },
  border: {
    border: '5 solid #343a40',
    padding: 30,
    height: '100%',
    justifyContent: 'space-between',
  },
  header: {
    textAlign: 'center',
  },
  govTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#c0392b',
    marginBottom: 4,
  },
  certTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    textDecoration: 'underline',
    marginBottom: 8,
  },
  subtext: {
    fontSize: 14,
    color: '#555',
    marginBottom: 20,
  },
  section: {
    marginVertical: 10,
    fontSize: 16,
    lineHeight: 1.5,
  },
  label: {
    fontWeight: 'bold',
    color: '#222',
  },
  info: {
    marginLeft: 10,
    color: '#333',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 40,
  },
  signature: {
    width: '40%',
    borderTop: '1 solid #000',
    textAlign: 'center',
    paddingTop: 5,
    fontSize: 12,
  },
  footer: {
    textAlign: 'center',
    marginTop: 30,
    fontSize: 12,
    color: '#777',
  },
})

const MarriageCertificate: React.FC<CertificateProps> = ({ application }) => {
  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.border}>
          <View style={styles.header}>
            <Text style={styles.govTitle}>Government of Nepal</Text>
            <Text style={styles.certTitle}>Marriage Certificate</Text>
            <Text style={styles.subtext}>This is an official record of legal civil marriage</Text>
          </View>

          <View>
            <Text style={styles.section}>
              <Text style={styles.label}>Husband:</Text>
              <Text style={styles.info}> {application.husbandName}</Text>
            </Text>
            <Text style={styles.section}>
              <Text style={styles.label}>Wife:</Text>
              <Text style={styles.info}> {application.wifeName}</Text>
            </Text>
            <Text style={styles.section}>
              <Text style={styles.label}>Date of Marriage:</Text>
              <Text style={styles.info}> {new Date(application.dateOfMarriage).toDateString()}</Text>
            </Text>
            <Text style={styles.section}>
              <Text style={styles.label}>Witness:</Text>
              <Text style={styles.info}> {application.witnessName}</Text>
            </Text>
            <Text style={styles.section}>
              <Text style={styles.label}>Witness Citizenship No.:</Text>
              <Text style={styles.info}> {application.witnessCitizenshipNo}</Text>
            </Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.signature}>Registrar Signature</Text>
            <Text style={styles.signature}>Witness Signature</Text>
          </View>

          <Text style={styles.footer}>
            This certificate is digitally generated by the Government of Nepal and does not require a physical signature.
          </Text>
        </View>
      </Page>
    </Document>
  )
}

export default MarriageCertificate
